import pytest
from teacher.models import Teacher


@pytest.mark.django_db
def test_teacher_create(teacher):
    """
        Testing method to check that teacher is creatable.
        :param teacher: teacher generated by factory (look for the FactoryBoy)
    """
    new_teacher = Teacher.objects.create(name=teacher.name, surname=teacher.surname, patronymic=teacher.patronymic)
    assert teacher.surname == new_teacher.surname


@pytest.mark.django_db
def test_teacher_delete():
    """
        Testing method to check that teacher (latest for the test) is deletable.
    """
    with pytest.raises(Teacher.DoesNotExist):
        last_teacher = Teacher.objects.last()
        last_teacher.delete()
        Teacher.objects.get(pk=last_teacher.id)
