# Generated by Django 3.2 on 2021-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210223_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='vote_counts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachersubjectsemester',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
