# Generated by Django 3.2 on 2021-06-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210521_1406'),
        ('voting', '0004_auto_20210520_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectsemester',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_semesters', to='teacher.teacher'),
        ),
    ]
