# Generated by Django 3.2 on 2021-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_year',
            field=models.PositiveSmallIntegerField(blank=True, default=9999, null=True),
        ),
    ]
