# Generated by Django 2.2.9 on 2020-05-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
