# Generated by Django 3.0.5 on 2020-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_teacher_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(default='https://secure.gravatar.com/avatar/0fb68a3652b2d19b550a3fca1e71d9cc?s=4729128&d=mm', null=True),
        ),
    ]
