# Generated by Django 3.0.5 on 2020-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_student_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semesters',
            field=models.SlugField(default=None, null=True),
        ),
    ]
