# Generated by Django 3.0.5 on 2020-05-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_auto_20200522_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semesters',
            field=models.SlugField(default=''),
        ),
    ]
