# Generated by Django 3.0.5 on 2020-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0004_auto_20200522_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semesters',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
