# Generated by Django 3.0.5 on 2020-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0004_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(choices=[(2019, '1 - бакалавриат'), (2018, '2 - бакалавриат'), (2017, '3 - бакалавриат'), (2016, '4 - бакалавриат'), (2015, '1 - магистратура'), (2014, '2 - магистратура')], default=1),
        ),
    ]
