# Generated by Django 3.0.5 on 2020-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_auto_20200522_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semesters',
            field=models.SlugField(blank=True, default='0', null=True),
        ),
    ]
