# Generated by Django 2.2.9 on 2020-06-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_auto_20200603_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semesters',
        ),
    ]
