# Generated by Django 3.0.5 on 2020-05-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0006_auto_20200522_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudTeachRateFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingapp.Teacher', verbose_name='Teacher')),
            ],
        ),
    ]
