# Generated by Django 2.2.9 on 2020-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0006_remove_student_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(max_length=4),
        ),
    ]
