# Generated by Django 3.0.5 on 2020-05-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0007_studteachratefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='studteachratefact',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.SmallIntegerField(choices=[(1, '1'), (-1, '-1'), (0, '0')], default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='teachersubjectcourse',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
