# Generated by Django 2.2.9 on 2020-06-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0007_auto_20200604_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingapp.AdmissionYear'),
        ),
    ]
