# Generated by Django 2.2.9 on 2020-06-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0008_auto_20200604_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votingapp.AdmissionYear'),
        ),
    ]
