# Generated by Django 3.2 on 2021-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_vote_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
