# Generated by Django 3.2 on 2021-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vote_counts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
