import pytest
import datetime as dt

from account.models import User


@pytest.mark.django_db
def test_name():
    """
        Checking that user's name is extracting correctly.
    """
    name = 'test'
    new_user = User.objects.create(email=f'{name}@stud.kpfu.ru', admission_year=dt.datetime.today().year - 1,
                                   password='password')
    assert name == new_user.name()


@pytest.mark.django_db
def test_user_creating(user):
    """
        Checking that user is creating correctly.
        :param user: user generated by factory (look for the FactoryBoy)
    """
    email = f'test{user.email}'
    new_user = User.objects.create(email=email, admission_year=user.admission_year,
                                   password=user.password)
    assert email == new_user.email


@pytest.mark.django_db
def test_superuser_creating(user):
    """
        Checking that superuser is creating correctly.
        :param user: user generated by factory (look for the FactoryBoy)
    """
    email = f'test{user.email}'
    new_user = User.objects.create_superuser(email=email, admission_year=user.admission_year,
                                            password=user.password)
    assert email == new_user.email
